[package]
name = "forge-image"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
forge-core = { path = "../forge-core" }
thiserror.workspace = true
image.workspace = true
kamadak-exif.workspace = true
webp.workspace = true
qrcode.workspace = true
rqrr.workspace = true
